-- 코드를 작성해주세요
SELECT II.ITEM_ID AS ITEM_ID, II.ITEM_NAME AS ITEM_NAME, II.RARITY AS RARITY
FROM ITEM_INFO II
LEFT JOIN ITEM_TREE IT
ON II.ITEM_ID = IT.PARENT_ITEM_ID
WHERE IT.ITEM_ID IS NULL
ORDER BY ITEM_ID DESC