SELECT FD.ID AS ID, COALESCE(CD.COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA FD
LEFT JOIN (
    SELECT PARENT_ID, COUNT(PARENT_ID) AS COUNT
    FROM ECOLI_DATA
    GROUP BY PARENT_ID
    HAVING PARENT_ID IS NOT NULL
) CD
ON FD.ID = CD.PARENT_ID