SELECT E1.ID AS ID, COALESCE(E2.COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA E1
LEFT JOIN (
    SELECT PARENT_ID, COUNT(ID) AS 'COUNT'
    FROM ECOLI_DATA
    GROUP BY PARENT_ID
    HAVING PARENT_ID IS NOT NULL
) E2
ON E1.ID = E2.PARENT_ID
ORDER BY ID