-- 코드를 입력하세요 15
SELECT USER_ID, PRODUCT_ID
FROM ONLINE_SALE
GROUP BY USER_ID, PRODUCT_ID
HAVING COUNT(PRODUCT_ID) > 1
ORDER BY USER_ID, PRODUCT_ID DESC;


# SELECT *
# FROM ONLINE_SALE
# ORDER BY USER_ID;