-- 코드를 입력하세요
SELECT YEAR(O.SALES_DATE) AS YEAR, MONTH(O.SALES_DATE) AS MONTH, 
COUNT(DISTINCT(O.USER_ID)) AS PUCHASED_USERS,
ROUND((COUNT(DISTINCT(U.USER_ID)) / (SELECT COUNT(*)
    FROM USER_INFO 
    WHERE YEAR(JOINED) = '2021')), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE O 
JOIN USER_INFO U ON O.USER_ID = U.USER_ID
WHERE YEAR(U.JOINED) = '2021'
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH