-- 코드를 입력하세요
SELECT P.PRODUCT_ID AS PRODUCT_ID, 
P.PRODUCT_NAME AS PRODUCT_NAME,
P.PRICE * SUM(AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT P
JOIN FOOD_ORDER O ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE DATE_FORMAT(O.PRODUCE_DATE, '%Y-%m') = '2022-05'
GROUP BY O.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID