SELECT UU.USER_ID AS USER_ID, UU.NICKNAME AS NICKNAME, SUM(UB.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD UB
JOIN USED_GOODS_USER UU
ON UB.WRITER_ID = UU.USER_ID
WHERE UB.STATUS = 'DONE'
GROUP BY UB.WRITER_ID
HAVING SUM(UB.PRICE) >= 700000
ORDER BY TOTAL_SALES