SELECT YEAR(ED1.DIFFERENTIATION_DATE) AS YEAR, (ED2.MAX_SIZE - ED1.SIZE_OF_COLONY) AS YEAR_DEV, ED1.ID AS ID
FROM ECOLI_DATA ED1
LEFT JOIN (
    SELECT MAX(SIZE_OF_COLONY) AS MAX_SIZE, YEAR(DIFFERENTIATION_DATE) AS YEAR
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) ED2
ON YEAR(ED1.DIFFERENTIATION_DATE) = ED2.YEAR
ORDER BY YEAR(ED1.DIFFERENTIATION_DATE), YEAR_DEV
