-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/', B.BOARD_ID, '/', F.FILE_ID, F.FILE_NAME, F.FILE_EXT) AS FILE_PATH
FROM (
    SELECT BOARD_ID, VIEWS
    FROM USED_GOODS_BOARD
    ORDER BY VIEWS DESC
    LIMIT 1
) B
JOIN USED_GOODS_FILE F ON B.BOARD_ID = F.BOARD_ID
ORDER BY B.VIEWS DESC, FILE_PATH DESC;